
export const FETCH_USER_SETTINGS_REQUEST = 'FETCH_USER_SETTINGS_REQUEST';
export const FETCH_USER_SETTINGS_SUCCESS = 'FETCH_USER_SETTINGS_SUCCESS';
export const FETCH_USER_SETTINGS_FAILURE = 'FETCH_USER_SETTINGS_FAILURE';

export const UPDATE_USER_SETTINGS_REQUEST = 'UPDATE_USER_SETTINGS_REQUEST';
export const UPDATE_USER_SETTINGS_SUCCESS = 'UPDATE_USER_SETTINGS_SUCCESS';
export const UPDATE_USER_SETTINGS_FAILURE = 'UPDATE_USER_SETTINGS_FAILURE';

export const UPDATE_USER_PROFILE_REQUEST = 'UPDATE_USER_PROFILE_REQUEST';
export const UPDATE_USER_PROFILE_SUCCESS = 'UPDATE_USER_PROFILE_SUCCESS';
export const UPDATE_USER_PROFILE_FAILURE = 'UPDATE_USER_PROFILE_FAILURE';

export const UPDATE_USER_JOB_REQUEST = 'UPDATE_USER_JOB_REQUEST';
export const UPDATE_USER_JOB_SUCCESS = 'UPDATE_USER_JOB_SUCCESS';
export const UPDATE_USER_JOB_FAILURE = 'UPDATE_USER_JOB_FAILURE';

export const UPDATE_USER_AVAILABILITY_REQUEST = 'UPDATE_USER_AVAILABILITY_REQUEST';
export const UPDATE_USER_AVAILABILITY_SUCCESS = 'UPDATE_USER_AVAILABILITY_SUCCESS';
export const UPDATE_USER_AVAILABILITY_FAILURE = 'UPDATE_USER_AVAILABILITY_FAILURE';

export const UPDATE_USER_NOTIFICATIONS_REQUEST = 'UPDATE_USER_NOTIFICATIONS_REQUEST';
export const UPDATE_USER_NOTIFICATIONS_SUCCESS = 'UPDATE_USER_NOTIFICATIONS_SUCCESS';
export const UPDATE_USER_NOTIFICATIONS_FAILURE = 'UPDATE_USER_NOTIFICATIONS_FAILURE';

export const UPDATE_USER_SECURITY_REQUEST = 'UPDATE_USER_SECURITY_REQUEST';
export const UPDATE_USER_SECURITY_SUCCESS = 'UPDATE_USER_SECURITY_SUCCESS';
export const UPDATE_USER_SECURITY_FAILURE = 'UPDATE_USER_SECURITY_FAILURE';

export const UPDATE_USER_ADMIN_SETTINGS_REQUEST = 'UPDATE_USER_ADMIN_SETTINGS_REQUEST';
export const UPDATE_USER_ADMIN_SETTINGS_SUCCESS = 'UPDATE_USER_ADMIN_SETTINGS_SUCCESS';
export const UPDATE_USER_ADMIN_SETTINGS_FAILURE = 'UPDATE_USER_ADMIN_SETTINGS_FAILURE';

export const UPDATE_USER_OPTIONAL_SETTINGS_REQUEST = 'UPDATE_USER_OPTIONAL_SETTINGS_REQUEST';
export const UPDATE_USER_OPTIONAL_SETTINGS_SUCCESS = 'UPDATE_USER_OPTIONAL_SETTINGS_SUCCESS';
export const UPDATE_USER_OPTIONAL_SETTINGS_FAILURE = 'UPDATE_USER_OPTIONAL_SETTINGS_FAILURE';
